from consts import *

class Options:

    POINTS_DISTANCE = DEFAULT_POINTS_DISTANCE 
    POINTS_RADIUS = DEFAULT_POINTS_RADIUS

    N_VERTICES_RANDGRAPH = DEFAULT_N_VERTICES_RANDGRAPH

    NEIGHBORS_INTERVAL = DEFAULT_NEIGHBORS_INTERVAL